var f;f||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&process.versions?.node&&"renderer"!=process.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha="undefined"!=typeof document?document.currentScript?.src:void 0;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=f);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),k=console.error.bind(console),m,p=!1,na,la=a=>a.startsWith("file://"),oa,t,u,pa,qa,v,w,x,y,A=0,B=null;
function ra(a){f.onAbort?.(a);a="Aborted("+a+")";k(a);p=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var sa;async function ta(a){if(!m)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==sa&&m)a=new Uint8Array(m);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}
async function ua(a,b){try{var c=await ta(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),ra(d)}}async function va(a){var b=sa;if(!m&&"function"==typeof WebAssembly.instantiateStreaming&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return ua(b,a)}
class wa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var xa=a=>{for(;0<a.length;)a.shift()(f)},ya=[],za=[],Aa=()=>{var a=f.preRun.shift();za.push(a)},Ba=!0,Ca=new TextDecoder,C=(a,b)=>{if(!a)return"";b=a+b;for(var c=a;!(c>=b)&&u[c];)++c;return Ca.decode(u.subarray(a,c))},Da=0,D={},Ea=a=>{a instanceof wa||"unwind"==a||fa(1,a)},Fa=a=>{na=a;Ba||0<Da||(f.onExit?.(a),p=!0);fa(a,new wa(a))},Ga=a=>{na=a;Fa(a)},Ha=()=>{if(!(Ba||0<Da))try{var a=na;na=a;Fa(a)}catch(b){Ea(b)}},Ia=a=>{if(!p)try{a(),Ha()}catch(b){Ea(b)}},Qa=(a,b)=>{Ja=a;Ka=b;if(F)if(La||=!0,0==
a)G=function(){setTimeout(Ma,Math.max(0,Na+b-performance.now())|0)};else if(1==a)G=function(){Oa(Ma)};else if(2==a){if("undefined"==typeof Pa)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Pa=d=>{c.push(d);if(ba){let e;(e=f).setImmediates??(e.setImmediates=[]);f.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Pa=setImmediate;
G=function(){Pa(Ma)}}},Za=(a,b,c,d,e)=>{function h(){return g<Ra?(Ha(),!1):!0}F=a;Sa=d;var g=Ra;La=!1;Ma=function(){if(!p)if(0<Ta.length){var l=Ta.shift();l.rd(l.ed);if(Ua){var n=Ua,q=0==n%1?n-1:Math.floor(n);Ua=l.hd?q:(8*n+(q+.5))/9}f.setStatus&&(l=f.statusMessage||"Please wait...",n=Ua??0,q=Va.nd??0,n?n<q?f.setStatus("{message} ({expected - remaining}/{expected})"):f.setStatus(l):f.setStatus(""));h()&&setTimeout(Ma,0)}else if(h())if(Wa=Wa+1|0,1==Ja&&1<Ka&&0!=Wa%Ka)G();else{0==Ja&&(Na=performance.now());
a:if(!p){for(l of Xa)if(!1===l())break a;Ia(a);for(n of Ya)n()}h()&&G()}};e||(0<b?Qa(0,1E3/b):Qa(1,1),G());if(c)throw"unwind";},La=!1,G=null,Ra=0,F=null,Sa=0,Ja=0,Ka=0,Wa=0,Ta=[],Xa=[],Ya=[];function $a(){G=null;Ra++}var ab=0;function Oa(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===ab)ab=b+1E3/60;else for(;b+2>=ab;)ab+=1E3/60;setTimeout(a,Math.max(ab-b,0))}}
var Va={},Na,Ma,Pa,Ua,bb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],H=a=>{a=2<a?C(a):a;return bb[a]||("undefined"!=typeof document?document.querySelector(a):null)},cb=a=>0>bb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},I;function db(a){var b=J.jc[a];b.target.removeEventListener(b.ic,b.Lc,b.kc);J.jc.splice(a,1)}function eb(){if(navigator.userActivation?navigator.userActivation.isActive:J.yc&&J.$c.wc){var a=J.oc;J.oc=[];for(var b of a)b.Bc(...b.Hc)}}
function K(a){if(!a.target)return-4;if(a.lc)a.Lc=function(c){++J.yc;J.$c=a;eb();a.mc(c);eb();--J.yc},a.target.addEventListener(a.ic,a.Lc,a.kc),J.jc.push(a);else for(var b=0;b<J.jc.length;++b)J.jc[b].target==a.target&&J.jc[b].ic==a.ic&&db(b--);return 0}function fb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var J={gd:0,sd:0,zc:0,vc:0,Fc:0,Dc:0,xc:0,ld:0,xd:0,kd:0,qd:0,Ac:0,Gd:0,Cc:0,ud(a,b,c){t.set(t.subarray(b,b+c),a)},zd(){for(;J.jc.length;)db(J.jc.length-1);J.oc=[]},yc:0,oc:[],jd(a,b,c){function d(h,g){if(h.length!=g.length)return!1;for(var l in h)if(h[l]!=g[l])return!1;return!0}for(var e of J.oc)if(e.Bc==a&&d(e.Hc,c))return;J.oc.push({Bc:a,Rc:b,Hc:c});J.oc.sort((h,g)=>h.Rc<g.Rc)},Bd(a){J.oc=J.oc.filter(b=>b.Bc!=a)},jc:[],Ad:(a,b)=>{for(var c=0;c<J.jc.length;++c)J.jc[c].target!=a||b&&b!=J.jc[c].ic||
db(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},L=(a,b,c)=>{var d=u;if(!(0<c))return 0;var e=b;c=b+c-1;for(var h=0;h<a.length;++h){var g=a.codePointAt(h);if(127>=g){if(b>=c)break;d[b++]=g}else if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6;d[b++]=128|g&63}else if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12;d[b++]=128|g>>6&63;d[b++]=128|g&63}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63;d[b++]=128|g>>6&63;d[b++]=128|g&63;h++}}d[b]=0;return b-
e},gb=(a,b,c,d,e,h)=>{J.xc||(J.xc=M(256));a={target:H(a),ic:h,lc:d,mc:(g=event)=>{var l=g.target.id?g.target.id:"",n=J.xc;L(fb(g.target),n+0,128);L(l,n+128,128);I.get(d)(e,n,b)&&g.preventDefault()},kc:c};return K(a)},hb=(a,b,c,d,e,h)=>{J.zc||(J.zc=M(160));a={target:H(a),ic:h,lc:d,mc:g=>{var l=J.zc;y[l>>3]=g.timeStamp;var n=l>>2;v[n+2]=g.location;t[l+12]=g.ctrlKey;t[l+13]=g.shiftKey;t[l+14]=g.altKey;t[l+15]=g.metaKey;t[l+16]=g.repeat;v[n+5]=g.charCode;v[n+6]=g.keyCode;v[n+7]=g.which;L(g.key||"",l+
32,32);L(g.code||"",l+64,32);L(g.char||"",l+96,32);L(g.locale||"",l+128,32);I.get(d)(e,l,b)&&g.preventDefault()},kc:c};return K(a)},ib=(a,b,c)=>{y[a>>3]=b.timeStamp;var d=a>>2;v[d+2]=b.screenX;v[d+3]=b.screenY;v[d+4]=b.clientX;v[d+5]=b.clientY;t[a+24]=b.ctrlKey;t[a+25]=b.shiftKey;t[a+26]=b.altKey;t[a+27]=b.metaKey;pa[2*d+14]=b.button;pa[2*d+15]=b.buttons;v[d+8]=b.movementX;v[d+9]=b.movementY;a=cb(c);v[d+10]=b.clientX-(a.left|0);v[d+11]=b.clientY-(a.top|0)},jb=(a,b,c,d,e,h)=>{J.vc||(J.vc=M(64));a=
H(a);return K({target:a,wc:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,ic:h,lc:d,mc:(g=event)=>{ib(J.vc,g,a);I.get(d)(e,J.vc,b)&&g.preventDefault()},kc:c})},kb=(a,b,c,d,e)=>{J.Ac||(J.Ac=M(257));return K({target:a,ic:e,lc:d,mc:(h=event)=>{var g=J.Ac,l=document.pointerLockElement||document.qc||document.Oc||document.Nc;t[g]=!!l;var n=l?.id||"";L(fb(l),g+1,128);L(n,g+129,128);I.get(d)(20,g,b)&&h.preventDefault()},kc:c})},lb=(a,b,c,d,e)=>K({target:a,ic:e,lc:d,mc:(h=event)=>{I.get(d)(38,0,b)&&h.preventDefault()},
kc:c}),mb=(a,b,c,d)=>{J.Dc||(J.Dc=M(36));a=H(a);return K({target:a,ic:"resize",lc:d,mc:(e=event)=>{if(e.target==a){var h=document.body;if(h){var g=J.Dc;v[g>>2]=0;v[g+4>>2]=h.clientWidth;v[g+8>>2]=h.clientHeight;v[g+12>>2]=innerWidth;v[g+16>>2]=innerHeight;v[g+20>>2]=outerWidth;v[g+24>>2]=outerHeight;v[g+28>>2]=pageXOffset|0;v[g+32>>2]=pageYOffset|0;I.get(d)(10,g,b)&&e.preventDefault()}}},kc:c})},nb=(a,b,c,d,e,h)=>{J.Cc||(J.Cc=M(1552));a=H(a);return K({target:a,wc:"touchstart"==h||"touchend"==h,ic:h,
lc:d,mc:g=>{var l={},n=g.touches;for(var q of n)q.Mc=q.Qc=0,l[q.identifier]=q;for(var r of g.changedTouches)r.Mc=1,l[r.identifier]=r;for(var z of g.targetTouches)l[z.identifier].Qc=1;n=J.Cc;y[n>>3]=g.timeStamp;t[n+12]=g.ctrlKey;t[n+13]=g.shiftKey;t[n+14]=g.altKey;t[n+15]=g.metaKey;q=n+16;r=cb(a);z=0;for(let E of Object.values(l))if(l=q>>2,v[l]=E.identifier,v[l+1]=E.screenX,v[l+2]=E.screenY,v[l+3]=E.clientX,v[l+4]=E.clientY,v[l+5]=E.pageX,v[l+6]=E.pageY,t[q+28]=E.Mc,t[q+29]=E.Qc,v[l+8]=E.clientX-(r.left|
0),v[l+9]=E.clientY-(r.top|0),q+=48,31<++z)break;v[n+8>>2]=z;I.get(d)(e,n,b)&&g.preventDefault()},kc:c})},N,ob=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,h)=>b.drawArraysInstancedANGLE(c,d,e,h),a.drawElementsInstanced=(c,d,e,h,g)=>b.drawElementsInstancedANGLE(c,d,e,h,g))},pb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=
c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},qb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},rb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},sb=1,O=[],P=[],tb=[],ub=[],Q=[],R=[],vb=[],wb=[],S=[],xb={},yb=4,zb=0,Ab=a=>{for(var b=sb++,c=a.length;c<b;c++)a[c]=null;return b},U=(a,b,c,d)=>{for(var e=0;e<a;e++){var h=N[c](),g=h&&Ab(d);h?(h.name=g,d[g]=h):T||=1282;v[b+4*e>>2]=g}},Cb=(a,b)=>{a.qc||(a.qc=a.getContext,a.getContext=function(d,e){e=a.qc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Pc?a.getContext("webgl2",b):a.getContext("webgl",b);return c?
Bb(c,b):0},Bb=(a,b)=>{var c=Ab(wb),d={handle:c,attributes:b,version:b.Pc,Gc:a};a.canvas&&(a.canvas.dd=d);wb[c]=d;("undefined"==typeof b.Kc||b.Kc)&&Db(d);return c},Db=a=>{a||=V;if(!a.cd){a.cd=!0;var b=a.Gc;b.wd=b.getExtension("WEBGL_multi_draw");b.pd=b.getExtension("EXT_polygon_offset_clamp");b.od=b.getExtension("EXT_clip_control");b.Hd=b.getExtension("WEBGL_polygon_mode");ob(b);pb(b);qb(b);b.md=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.td=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");
2<=a.version&&(b.Jc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Jc)b.Jc=b.getExtension("EXT_disjoint_timer_query");rb(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},T,V,Eb=(a,b,c,d,e,h)=>{a={target:H(a),ic:h,lc:d,mc:(g=event)=>{I.get(d)(e,0,b)&&g.preventDefault()},kc:c};K(a)},Fb=(a,b,c,d)=>{J.Fc||(J.Fc=M(96));return K({target:a,wc:!0,ic:"wheel",lc:d,mc:(e=event)=>{var h=J.Fc;ib(h,e,a);y[h+64>>3]=e.deltaX;y[h+72>>3]=e.deltaY;y[h+80>>
3]=e.deltaZ;v[h+88>>2]=e.deltaMode;I.get(d)(9,h,b)&&e.preventDefault()},kc:c})},Gb=["default","low-power","high-performance"],Hb={},Jb=()=>{if(!Ib){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.language||"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in Hb)void 0===Hb[b]?delete a[b]:a[b]=Hb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Ib=c}return Ib},Ib,Kb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);
127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Lb=[null,[],[]],Mb=[],Nb=()=>{var a=rb(N);return a=a.concat(a.map(b=>"GL_"+b))},Ob=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=N.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>V.version){T||=1282;return}c=Nb().length;break;case 33307:case 33308:if(2>V.version){T||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=N.getParameter(a),typeof d){case "number":c=
d;break;case "boolean":c=d?1:0;break;case "string":T||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=0;break;default:T||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)v[b+4*a>>2]=d[a];return}try{c=
d.name|0}catch(e){T||=1280;k(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:T||=1280;k(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}v[b>>2]=c}else T||=1281},Pb=a=>{var b=Kb(a)+1,c=M(b);c&&L(a,c,b);return c},Qb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Rb=a=>{a-=5120;return 0==a?t:1==a?u:2==a?pa:4==a?v:6==a?x:5==a||28922==a||28520==a||30779==a||30782==
a?w:qa},W=a=>{var b=N.ad;if(b){var c=b.rc[a];"number"==typeof c&&(b.rc[a]=c=N.getUniformLocation(b,b.Yc[a]+(0<c?`[${c}]`:"")));return c}T||=1282},X=[],Sb=[],Ub=a=>{var b=Kb(a)+1,c=Tb(b);L(a,c,b);return c},Xb=a=>{var b=Vb();a();Wb(b)};f.requestAnimationFrame=Oa;f.pauseMainLoop=$a;f.resumeMainLoop=function(){Ra++;var a=Ja,b=Ka,c=F;F=null;Za(c,0,!1,Sa,!0);Qa(a,b);G()};f.preMainLoop&&Xa.push(f.preMainLoop);f.postMainLoop&&Ya.push(f.postMainLoop);for(let a=0;32>a;++a)Mb.push(Array(a));
for(var Yb=new Float32Array(288),Y=0;288>=Y;++Y)X[Y]=Yb.subarray(0,Y);var Zb=new Int32Array(288);for(Y=0;288>=Y;++Y)Sb[Y]=Zb.subarray(0,Y);f.noExitRuntime&&(Ba=f.noExitRuntime);f.print&&(ma=f.print);f.printErr&&(k=f.printErr);f.wasmBinary&&(m=f.wasmBinary);f.arguments&&(da=f.arguments);f.thisProgram&&(ea=f.thisProgram);
var $b,ac,bc,cc,dc,ec,fc,M,Wb,Tb,Vb,gc={da:function(){return 0},ob:function(){return 0},pb:function(){},Sa:()=>ra(""),ib:()=>{Ba=!1;Da=0},jb:(a,b)=>{D[a]&&(clearTimeout(D[a].id),delete D[a]);if(!b)return 0;var c=setTimeout(()=>{delete D[a];Ia(()=>fc(a,performance.now()))},b);D[a]={id:c,Fd:b};return 0},Ya:()=>{$a();F=null},P:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,sa:(a,b,c)=>{a=H(a);if(!a)return-4;a=cb(a);y[b>>3]=a.width;y[c>>3]=a.height;return 0},Za:()=>performance.now(),cb:(a,
b)=>{function c(d){I.get(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},Ua:()=>{ra("OOM")},S:(a,b,c,d)=>gb(a,b,c,d,12,"blur"),O:(a,b,c)=>{a=H(a);if(!a)return-4;a.width=b;a.height=c;return 0},T:(a,b,c,d)=>gb(a,b,c,d,13,"focus"),fa:(a,b,c,d)=>hb(a,b,c,d,2,"keydown"),$:(a,b,c,d)=>hb(a,b,c,d,1,"keypress"),ba:(a,b,c,d)=>hb(a,b,c,d,3,"keyup"),db:(a,b,c)=>{a=I.get(a);Za(a,b,c)},C:(a,b,c,d)=>jb(a,b,c,d,5,"mousedown"),ma:(a,b,c,d)=>jb(a,b,c,d,33,"mouseenter"),ka:(a,b,c,d)=>jb(a,b,c,d,34,
"mouseleave"),ra:(a,b,c,d)=>jb(a,b,c,d,8,"mousemove"),x:(a,b,c,d)=>jb(a,b,c,d,6,"mouseup"),V:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.qc||document.body.Oc||document.body.Nc))return-1;a=H(a);if(!a)return-4;kb(a,b,c,d,"mozpointerlockchange");kb(a,b,c,d,"webkitpointerlockchange");kb(a,b,c,d,"mspointerlockchange");return kb(a,b,c,d,"pointerlockchange")},U:(a,b,c,d)=>{if(!document||!(document.body.requestPointerLock||document.body.qc||document.body.Oc||
document.body.Nc))return-1;a=H(a);if(!a)return-4;lb(a,b,c,d,"mozpointerlockerror");lb(a,b,c,d,"webkitpointerlockerror");lb(a,b,c,d,"mspointerlockerror");return lb(a,b,c,d,"pointerlockerror")},X:(a,b,c,d)=>mb(a,b,c,d),W:(a,b,c,d)=>nb(a,b,c,d,25,"touchcancel"),Y:(a,b,c,d)=>nb(a,b,c,d,23,"touchend"),Z:(a,b,c,d)=>nb(a,b,c,d,24,"touchmove"),_:(a,b,c,d)=>nb(a,b,c,d,22,"touchstart"),R:(a,b,c,d)=>{Eb(a,b,c,d,31,"webglcontextlost");return 0},Q:(a,b,c,d)=>{Eb(a,b,c,d,32,"webglcontextrestored");return 0},ia:(a,
b,c,d)=>(a=H(a))?"undefined"!=typeof a.onwheel?Fb(a,b,c,d):-1:-4,Oa:(a,b)=>{var c=b>>2;b={alpha:!!t[b+0],depth:!!t[b+1],stencil:!!t[b+2],antialias:!!t[b+3],premultipliedAlpha:!!t[b+4],preserveDrawingBuffer:!!t[b+5],powerPreference:Gb[v[c+2]],failIfMajorPerformanceCaveat:!!t[b+12],Pc:v[c+4],vd:v[c+5],Kc:t[b+24],bd:t[b+25],yd:v[c+7],Cd:t[b+32]};a=H(a);return!a||b.bd?0:Cb(a,b)},Ka:a=>{V=wb[a];f.ctx=N=V?.Gc;return!a||N?0:-5},kb:(a,b)=>{var c=0,d=0,e;for(e of Jb()){var h=b+c;w[a+d>>2]=h;c+=L(e,h,Infinity)+
1;d+=4}return 0},lb:(a,b)=>{var c=Jb();w[a>>2]=c.length;a=0;for(var d of c)a+=Kb(d)+1;w[b>>2]=a;return 0},ca:()=>52,nb:()=>52,mb:function(){return 70},Ta:(a,b,c,d)=>{for(var e=0,h=0;h<c;h++){var g=w[b>>2],l=w[b+4>>2];b+=8;for(var n=0;n<l;n++){var q=a,r=u[g+n],z=Lb[q];if(0===r||10===r){q=1===q?ma:k;for(r=0;z[r]&&!(NaN<=r);)++r;r=Ca.decode(z.buffer?z.subarray(0,r):new Uint8Array(z.slice(0,r)));q(r);z.length=0}else z.push(r)}e+=l}w[d>>2]=e;return 0},t:a=>N.activeTexture(a),p:(a,b)=>{N.attachShader(P[a],
R[b])},b:(a,b)=>{35051==a?N.Ic=b:35052==a&&(N.pc=b);N.bindBuffer(a,O[b])},ja:(a,b,c)=>{N.bindBufferBase(a,b,O[c])},Tb:(a,b,c,d,e)=>{N.bindBufferRange(a,b,O[c],d,e)},f:(a,b)=>{N.bindFramebuffer(a,tb[b])},ya:(a,b)=>{N.bindRenderbuffer(a,ub[b])},s:(a,b)=>{N.bindSampler(a,S[b])},g:(a,b)=>{N.bindTexture(a,Q[b])},N:a=>{N.bindVertexArray(vb[a])},pa:(a,b,c,d)=>N.blendColor(a,b,c,d),qa:(a,b)=>N.blendEquationSeparate(a,b),u:(a,b,c,d)=>N.blendFuncSeparate(a,b,c,d),Ab:(a,b,c,d,e,h,g,l,n,q)=>N.blitFramebuffer(a,
b,c,d,e,h,g,l,n,q),La:(a,b,c,d)=>{2<=V.version?c&&b?N.bufferData(a,u,d,c,b):N.bufferData(a,b,d):N.bufferData(a,c?u.subarray(c,c+b):b,d)},J:(a,b,c,d)=>{2<=V.version?c&&N.bufferSubData(a,b,u,d,c):N.bufferSubData(a,b,u.subarray(d,d+c))},qb:a=>N.checkFramebufferStatus(a),wa:(a,b,c,d)=>N.clearBufferfi(a,b,c,d),w:(a,b,c)=>{N.clearBufferfv(a,b,x,c>>2)},va:(a,b,c)=>{N.clearBufferiv(a,b,v,c>>2)},l:(a,b,c,d)=>{N.colorMask(!!a,!!b,!!c,!!d)},tb:a=>{N.compileShader(R[a])},Ga:(a,b,c,d,e,h,g,l,n)=>{2<=V.version?
N.pc||!l?N.compressedTexSubImage2D(a,b,c,d,e,h,g,l,n):N.compressedTexSubImage2D(a,b,c,d,e,h,g,u,n,l):N.compressedTexSubImage2D(a,b,c,d,e,h,g,u.subarray(n,n+l))},Fa:(a,b,c,d,e,h,g,l,n,q,r)=>{N.pc?N.compressedTexSubImage3D(a,b,c,d,e,h,g,l,n,q,r):N.compressedTexSubImage3D(a,b,c,d,e,h,g,l,n,u,r,q)},Da:()=>{var a=Ab(P),b=N.createProgram();b.name=a;b.uc=b.sc=b.tc=0;b.Ec=1;P[a]=b;return a},vb:a=>{var b=Ab(R);R[b]=N.createShader(a);return b},oa:a=>N.cullFace(a),wb:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*
c>>2],e=O[d];e&&(N.deleteBuffer(e),e.name=0,O[d]=null,d==N.Ic&&(N.Ic=0),d==N.pc&&(N.pc=0))}},q:(a,b)=>{for(var c=0;c<a;++c){var d=v[b+4*c>>2],e=tb[d];e&&(N.deleteFramebuffer(e),e.name=0,tb[d]=null)}},i:a=>{if(a){var b=P[a];b?(N.deleteProgram(b),b.name=0,P[a]=null):T||=1281}},K:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=ub[d];e&&(N.deleteRenderbuffer(e),e.name=0,ub[d]=null)}},L:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=S[d];e&&(N.deleteSampler(e),e.name=0,S[d]=null)}},h:a=>{if(a){var b=
R[a];b?(N.deleteShader(b),R[a]=null):T||=1281}},m:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=Q[d];e&&(N.deleteTexture(e),e.name=0,Q[d]=null)}},Na:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2];N.deleteVertexArray(vb[d]);vb[d]=null}},n:a=>N.depthFunc(a),o:a=>{N.depthMask(!!a)},c:a=>N.disable(a),la:a=>{N.disableVertexAttribArray(a)},Cb:(a,b,c)=>{N.drawArrays(a,b,c)},Db:(a,b,c,d)=>{N.drawArraysInstanced(a,b,c,d)},B:(a,b)=>{for(var c=Mb[a],d=0;d<a;d++)c[d]=v[b+4*d>>2];N.drawBuffers(c)},Fb:(a,b,
c,d)=>{N.drawElements(a,b,c,d)},Eb:(a,b,c,d,e)=>{N.drawElementsInstanced(a,b,c,d,e)},e:a=>N.enable(a),Pb:a=>{N.enableVertexAttribArray(a)},A:(a,b,c,d)=>{N.framebufferRenderbuffer(a,b,c,ub[d])},ga:(a,b,c,d,e)=>{N.framebufferTexture2D(a,b,c,Q[d],e)},rb:(a,b,c,d,e)=>{N.framebufferTextureLayer(a,b,Q[c],d,e)},na:a=>N.frontFace(a),Ma:(a,b)=>{U(a,b,"createBuffer",O)},M:(a,b)=>{U(a,b,"createFramebuffer",tb)},za:(a,b)=>{U(a,b,"createRenderbuffer",ub)},Ea:(a,b)=>{U(a,b,"createSampler",S)},Ja:(a,b)=>{U(a,b,
"createTexture",Q)},Qa:(a,b)=>{U(a,b,"createVertexArray",vb)},Aa:(a,b)=>N.getAttribLocation(P[a],C(b)),a:(a,b)=>Ob(a,b),Ca:(a,b,c,d)=>{a=N.getProgramInfoLog(P[a]);null===a&&(a="(unknown error)");b=0<b&&d?L(a,d,b):0;c&&(v[c>>2]=b)},E:(a,b,c)=>{if(c)if(a>=sb)T||=1281;else if(a=P[a],35716==b)a=N.getProgramInfoLog(a),null===a&&(a="(unknown error)"),v[c>>2]=a.length+1;else if(35719==b){if(!a.uc){var d=N.getProgramParameter(a,35718);for(b=0;b<d;++b)a.uc=Math.max(a.uc,N.getActiveUniform(a,b).name.length+
1)}v[c>>2]=a.uc}else if(35722==b){if(!a.sc)for(d=N.getProgramParameter(a,35721),b=0;b<d;++b)a.sc=Math.max(a.sc,N.getActiveAttrib(a,b).name.length+1);v[c>>2]=a.sc}else if(35381==b){if(!a.tc)for(d=N.getProgramParameter(a,35382),b=0;b<d;++b)a.tc=Math.max(a.tc,N.getActiveUniformBlockName(a,b).length+1);v[c>>2]=a.tc}else v[c>>2]=N.getProgramParameter(a,b);else T||=1281},sb:(a,b,c,d)=>{a=N.getShaderInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?L(a,d,b):0;c&&(v[c>>2]=b)},ha:(a,b,c)=>{c?35716==b?
(a=N.getShaderInfoLog(R[a]),null===a&&(a="(unknown error)"),v[c>>2]=a?a.length+1:0):35720==b?(a=N.getShaderSource(R[a]),v[c>>2]=a?a.length+1:0):v[c>>2]=N.getShaderParameter(R[a],b):T||=1281},Ra:(a,b)=>{if(2>V.version)return T||=1282,0;var c=xb[a];if(c)return 0>b||b>=c.length?(T||=1281,0):c[b];switch(a){case 7939:return c=Nb().map(Pb),c=xb[a]=c,0>b||b>=c.length?(T||=1281,0):c[b];default:return T||=1280,0}},D:(a,b)=>{b=C(b);if(a=P[a]){var c=a,d=c.rc,e=c.Zc,h;if(!d){c.rc=d={};c.Yc={};var g=N.getProgramParameter(c,
35718);for(h=0;h<g;++h){var l=N.getActiveUniform(c,h);var n=l.name;l=l.size;var q=Qb(n);q=0<q?n.slice(0,q):n;var r=c.Ec;c.Ec+=l;e[q]=[l,r];for(n=0;n<l;++n)d[r]=n,c.Yc[r++]=q}}c=a.rc;d=0;e=b;h=Qb(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,e=b.slice(0,h));if((e=a.Zc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||N.getUniformLocation(a,b)))return d}else T||=1281;return-1},zb:(a,b,c)=>{for(var d=Mb[b],e=0;e<b;e++)d[e]=v[c+4*e>>2];N.invalidateFramebuffer(a,d)},F:a=>{a=P[a];N.linkProgram(a);a.rc=0;a.Zc={}},Pa:(a,b)=>{3317==
a?yb=b:3314==a&&(zb=b);N.pixelStorei(a,b)},v:(a,b)=>N.polygonOffset(a,b),Bb:a=>N.readBuffer(a),xa:(a,b,c,d,e)=>N.renderbufferStorageMultisample(a,b,c,d,e),G:(a,b,c)=>{N.samplerParameterf(S[a],b,c)},d:(a,b,c)=>{N.samplerParameteri(S[a],b,c)},y:(a,b,c,d)=>N.scissor(a,b,c,d),ub:(a,b,c,d)=>{for(var e="",h=0;h<b;++h)e+=C(w[c+4*h>>2],d?w[d+4*h>>2]:void 0);N.shaderSource(R[a],e)},yb:(a,b,c)=>N.stencilFunc(a,b,c),ua:(a,b,c,d)=>N.stencilFuncSeparate(a,b,c,d),k:a=>N.stencilMask(a),xb:(a,b,c)=>N.stencilOp(a,
b,c),ta:(a,b,c,d)=>N.stencilOpSeparate(a,b,c,d),Ia:(a,b,c,d,e)=>N.texStorage2D(a,b,c,d,e),Ha:(a,b,c,d,e,h)=>N.texStorage3D(a,b,c,d,e,h),I:(a,b,c,d,e,h,g,l,n)=>{if(2<=V.version){if(N.pc){N.texSubImage2D(a,b,c,d,e,h,g,l,n);return}if(n){var q=Rb(l);N.texSubImage2D(a,b,c,d,e,h,g,l,q,n>>>31-Math.clz32(q.BYTES_PER_ELEMENT));return}}if(n){q=Rb(l);var r=h*((zb||e)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[g-6402]||1)*q.BYTES_PER_ELEMENT+yb-1&-yb);n=q.subarray(n>>>31-Math.clz32(q.BYTES_PER_ELEMENT),
n+r>>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else n=null;N.texSubImage2D(a,b,c,d,e,h,g,l,n)},H:(a,b,c,d,e,h,g,l,n,q,r)=>{if(N.pc)N.texSubImage3D(a,b,c,d,e,h,g,l,n,q,r);else if(r){var z=Rb(q);N.texSubImage3D(a,b,c,d,e,h,g,l,n,q,z,r>>>31-Math.clz32(z.BYTES_PER_ELEMENT))}else N.texSubImage3D(a,b,c,d,e,h,g,l,n,q,null)},Ob:(a,b,c)=>{if(2<=V.version)b&&N.uniform1fv(W(a),x,c>>2,b);else{if(288>=b)for(var d=X[b],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);N.uniform1fv(W(a),d)}},Ba:(a,b)=>{N.uniform1i(W(a),
b)},Kb:(a,b,c)=>{if(2<=V.version)b&&N.uniform1iv(W(a),v,c>>2,b);else{if(288>=b)for(var d=Sb[b],e=0;e<b;++e)d[e]=v[c+4*e>>2];else d=v.subarray(c>>2,c+4*b>>2);N.uniform1iv(W(a),d)}},Nb:(a,b,c)=>{if(2<=V.version)b&&N.uniform2fv(W(a),x,c>>2,2*b);else{if(144>=b){b*=2;for(var d=X[b],e=0;e<b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2]}else d=x.subarray(c>>2,c+8*b>>2);N.uniform2fv(W(a),d)}},Jb:(a,b,c)=>{if(2<=V.version)b&&N.uniform2iv(W(a),v,c>>2,2*b);else{if(144>=b){b*=2;for(var d=Sb[b],e=0;e<b;e+=2)d[e]=
v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2]}else d=v.subarray(c>>2,c+8*b>>2);N.uniform2iv(W(a),d)}},Mb:(a,b,c)=>{if(2<=V.version)b&&N.uniform3fv(W(a),x,c>>2,3*b);else{if(96>=b){b*=3;for(var d=X[b],e=0;e<b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2]}else d=x.subarray(c>>2,c+12*b>>2);N.uniform3fv(W(a),d)}},Ib:(a,b,c)=>{if(2<=V.version)b&&N.uniform3iv(W(a),v,c>>2,3*b);else{if(96>=b){b*=3;for(var d=Sb[b],e=0;e<b;e+=3)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2]}else d=
v.subarray(c>>2,c+12*b>>2);N.uniform3iv(W(a),d)}},Lb:(a,b,c)=>{if(2<=V.version)b&&N.uniform4fv(W(a),x,c>>2,4*b);else{if(72>=b){var d=X[4*b],e=x;c>>=2;b*=4;for(var h=0;h<b;h+=4){var g=c+h;d[h]=e[g];d[h+1]=e[g+1];d[h+2]=e[g+2];d[h+3]=e[g+3]}}else d=x.subarray(c>>2,c+16*b>>2);N.uniform4fv(W(a),d)}},Hb:(a,b,c)=>{if(2<=V.version)b&&N.uniform4iv(W(a),v,c>>2,4*b);else{if(72>=b){b*=4;for(var d=Sb[b],e=0;e<b;e+=4)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2],d[e+3]=v[c+(4*e+12)>>2]}else d=
v.subarray(c>>2,c+16*b>>2);N.uniform4iv(W(a),d)}},Gb:(a,b,c,d)=>{if(2<=V.version)b&&N.uniformMatrix4fv(W(a),!!c,x,d>>2,16*b);else{if(18>=b){var e=X[16*b],h=x;d>>=2;b*=16;for(var g=0;g<b;g+=16){var l=d+g;e[g]=h[l];e[g+1]=h[l+1];e[g+2]=h[l+2];e[g+3]=h[l+3];e[g+4]=h[l+4];e[g+5]=h[l+5];e[g+6]=h[l+6];e[g+7]=h[l+7];e[g+8]=h[l+8];e[g+9]=h[l+9];e[g+10]=h[l+10];e[g+11]=h[l+11];e[g+12]=h[l+12];e[g+13]=h[l+13];e[g+14]=h[l+14];e[g+15]=h[l+15]}}else e=x.subarray(d>>2,d+64*b>>2);N.uniformMatrix4fv(W(a),!!c,e)}},
j:a=>{a=P[a];N.useProgram(a);N.ad=a},Qb:(a,b)=>{N.vertexAttribDivisor(a,b)},Rb:(a,b,c,d,e)=>{N.vertexAttribIPointer(a,b,c,d,e)},Sb:(a,b,c,d,e,h)=>{N.vertexAttribPointer(a,b,c,!!d,e,h)},z:(a,b,c,d)=>N.viewport(a,b,c,d),hb:Fa,gb:function(){f.Sc=a=>{0!=bc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",f.Sc)},fb:function(){f.Xc=a=>{const b=a.clipboardData.getData("text");Xb(()=>{const c=Ub(b);ac(c)})};window.addEventListener("paste",f.Xc)},eb:function(){f.Dd=[];f.Tc=
b=>{b.stopPropagation();b.preventDefault()};f.Uc=b=>{b.stopPropagation();b.preventDefault()};f.Vc=b=>{b.stopPropagation();b.preventDefault()};f.Wc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;f.Ed=c;cc(c.length);for(let e=0;e<c.length;e++)Xb(()=>{const h=Ub(c[e].name);dc(e,h)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);ec(b.clientX,b.clientY,d)};const a=f.nc;a.addEventListener("dragenter",f.Tc,!1);a.addEventListener("dragleave",f.Uc,
!1);a.addEventListener("dragover",f.Vc,!1);a.addEventListener("drop",f.Wc,!1)},$a:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},Ub:function(a,b){0!==b&&(document.title=C(b));a=C(a);void 0!==f.canvas&&("object"===typeof f.canvas?bb[a]=f.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));f.nc=H(a);f.nc||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);f.nc.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",
a)},Xa:function(){window.removeEventListener("beforeunload",f.Sc)},Wa:function(){window.removeEventListener("paste",f.Xc)},Va:function(){const a=f.nc;a.removeEventListener("dragenter",f.Tc);a.removeEventListener("dragleave",f.Uc);a.removeEventListener("dragover",f.Vc);a.removeEventListener("drop",f.Wc)},r:function(){f.nc&&f.nc.requestPointerLock&&f.nc.requestPointerLock()},bb:function(a,b){if(f.nc){if(0===b)a="none";else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;
case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}f.nc.style.cursor=a}},_a:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),h=e.createImageData(a,b);h.data.set(u.subarray(c,c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";
a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},ab:function(a){a=C(a);const b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},ea:function(){return navigator.userAgent.includes("Macintosh")?
1:0},aa:function(a,b){b=C(b);switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}},Z;
(async function(){function a(c){Z=c.exports;oa=Z.Vb;c=oa.buffer;t=new Int8Array(c);pa=new Int16Array(c);u=new Uint8Array(c);qa=new Uint16Array(c);v=new Int32Array(c);w=new Uint32Array(c);x=new Float32Array(c);y=new Float64Array(c);new BigInt64Array(c);new BigUint64Array(c);I=Z.hc;c=Z;f._main=$b=c.Xb;f.__sapp_emsc_onpaste=ac=c.Yb;f.__sapp_html5_get_ask_leave_site=bc=c.Zb;f.__sapp_emsc_begin_drop=cc=c._b;f.__sapp_emsc_drop=dc=c.$b;f.__sapp_emsc_end_drop=ec=c.ac;f.__sapp_emsc_invoke_fetch_cb=c.bc;fc=
c.cc;M=c.dc;Wb=c.ec;Tb=c.fc;Vb=c.gc;A--;f.monitorRunDependencies?.(A);0==A&&B&&(c=B,B=null,c());return Z}A++;f.monitorRunDependencies?.(A);var b={a:gc};if(f.instantiateWasm)return new Promise(c=>{f.instantiateWasm(b,(d,e)=>{c(a(d,e))})});sa??=f.locateFile?f.locateFile("index.wasm",ia):ia+"index.wasm";return a((await va(b)).instance)})();function hc(a=[]){var b=$b;a.unshift(ea);var c=a.length,d=Tb(4*(c+1)),e=d;a.forEach(g=>{w[e>>2]=Ub(g);e+=4});w[e>>2]=0;try{var h=b(c,d);Ga(h)}catch(g){Ea(g)}}
function ic(a=da){function b(){f.calledRun=!0;if(!p){Z.Wb();f.onRuntimeInitialized?.();f.noInitialRun||hc(a);if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var c=f.postRun.shift();ya.push(c)}xa(ya)}}if(0<A)B=ic;else{if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Aa();xa(za);0<A?B=ic:f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);b()},1)):b()}}
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.shift()();ic();
